language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
  # Before you can really do this, you have to peform the initial deploy
  #   zappa deploy <stage>
  # where <stage> is one of the defined stages. dev is a good choice, and 
  # in fact is what's defined in zappa_settings.json
- zappa update dev